[package]
name = "pliocene"
version = "0.1.0"
authors = ["floppyhammer <tannhauser_chen@outlook.com>"]
edition = "2021"

[workspace]
members = [
    "crates/*",
]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[[example]]
name = "2d"
path = "examples/2d.rs"

[[example]]
name = "3d"
path = "examples/3d.rs"

[[example]]
name = "text"
path = "examples/text.rs"
