[package]
name = "eureka"
version = "0.1.0"
authors = ["floppyhammer <tannhauser_chen@outlook.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24", default-features = false, features = [
    "jpeg",
    "png",
] }
winit = "0.26"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13.1"
pollster = "0.2"
bytemuck = { version = "1.4", features = ["derive"] }
anyhow = "1.0"
# For .obj loading.
tobj = "3.2"

chrono = "0.4.19"
serde_json = "1.0"
# For vector rendering.
lyon = "1.0.0"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
