[package]
name = "flint"
version = "0.1.0"
authors = ["floppyhammer <tannhauser_chen@outlook.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24", default-features = false, features = [
    "jpeg",
    "png",
] }
winit = "0.26"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2"
bytemuck = { version = "1.4", features = ["derive"] }
anyhow = "1.0"
tobj = "3.2"

egui = "0.17"
epi = "0.17"
egui-winit = "0.17"
egui_wgpu_backend = "0.17"
chrono = "0.4.19"
serde_json = "1.0"
egui_extras = { version = "0.17", features = ["image", "svg"] }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
