[package]
name = "eureka"
version = "0.1.0"
authors = ["floppyhammer <tannhauser_chen@outlook.com>"]
edition = "2021"
resolver = "2"

[dependencies]
image = { version = "0.24", default-features = false, features = [
    "jpeg",
    "png",
] }
winit = "0.28.2"
cgmath = "0.18"
env_logger = "0.10.0"
log = "0.4"
wgpu = "0.16.0"
pollster = "0.3.0"
bytemuck = { version = "1.4", features = ["derive"] }
anyhow = "1.0"
# For .obj loading.
tobj = "4.0.0"
chrono = "0.4.19"
# For JSON parsing.
serde_json = "1.0"
# For vector rendering.
lyon = "1.0.0"
# Tree structure.
indextree = "4.4.0"
# Text rasterization.
fontdue = "0.7.2"
# Text shaping.
rustybuzz = "0.7.0"
allsorts = "0.14.0"
# Language detection.
whatlang = "0.16.2"
# Text bidi.
unicode-bidi = "0.3.8"
# Finding system fonts.
font-kit = "0.11.0"
# For splitting grapheme clusters.
unicode-segmentation = "1.10.0"
# SVG parsing.
usvg = "0.32.0"
# Assets management.
assets_manager = { version = "0.10.0", features = ["hot-reloading"] }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[[example]]
name = "2d"
path = "examples/2d.rs"

[[example]]
name = "3d"
path = "examples/3d.rs"

[[example]]
name = "text"
path = "examples/text.rs"
